#  import the python files defining the Screens


#  include the kv files for the other Screens
#: include templates_new/authorization_or_registration_screen.kv
#: include templates_new/login_screen.kv
#: include templates_new/registration_screen.kv
#: include templates_new/home_screen.kv


WindowManager:
    transition: NoTransition()
    Home_screen:
    Login_screen:
    Registration_screen:
    Authorization_or_registration_screen: