Screen

    MDCard:
        size_hint: None, None
        size: 300, 500
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        elevation: 10
        padding: 25
        spacing: 25
        orientation: 'vertical'

        MDLabel:
            id: welcome_label
            text: "Привет"
            font_size: 40
            font_name: 'productsans.ttf'
            halign: 'center'
            valign: 'top'
